var products = [
    {
    "id": 0,
    "title": "-- Select Anyone --",
    "price": "",
    "description": "",
    "brand": "",
    "image": "images/No_Image.png",
},

{
    "id": 1,
    "title": "Hp M27h FHD Monitor",
    "price": 229.99,
    "description": "FHD (1920 x 1080) 1000 15ms GtG (with overdrive) Certainly! Here's a possible description for the HP M27h FHD Monitor:Immerse yourself in stunning visuals with the HP M27h FHD Monitor, a sleek and sophisticated display designed to elevate your viewing experience. Boasting a 27-inch Full HD screen, this monitor delivers crystal-clear imagery with vibrant colors and sharp details, making it ideal for work, entertainment, and creative endeavors.The ultra-thin bezels create an expansive and immersive viewing area, allowing you to focus on the content without distractions. With a resolution of 1920 x 1080 pixels, the HP M27h ensures that every image is rendered with precision and clarity, whether you're editing photos, watching movies, or working on detailed documents",
    "brand": "HP",
    "image": "images/p.monitor.1.png",
},
{
    "id": 2,
    "title": "OMEN by HP Gaming Monitor",
    "price": 159999,
    "description": "Dive into the heart of gaming intensity with the OMEN by HP Gaming Monitor, a powerhouse display designed for the most immersive gaming experiences. This 27-inch monitor combines cutting-edge technology with sleek aesthetics to deliver stunning visuals and responsive performance.Featuring a WQHD (2560 x 1440) resolution, the OMEN monitor ensures that every detail is sharp and vibrant, bringing your games to life with clarity and precision. The 165Hz refresh rate and 1ms response time provide ultra-smooth gameplay, capturing every frame with speed and accuracy, while AMD FreeSync technology eliminates screen tearing for a seamless and tear-free gaming experience.",
    "brand": "HP",
    "image": "images/p.monitor.2.png",
},
{
    "id": 3,
    "title": "HP M27fw FHD Monitor",
    "price": 169.99,
    "description": "Experience the perfect blend of style and performance with the HP M27fw FHD Monitor. This 27-inch Full HD display delivers crisp visuals and vibrant colors, making it an ideal choice for both work and entertainment.The micro-edge, virtually borderless design provides an immersive viewing experience, allowing you to focus on your content without distractions. With a resolution of 1920 x 1080 pixels, every detail is rendered with clarity, whether you're working on documents, watching videos, or browsing the web.",
    "brand": "HP",
    "image": "images/p.monitor3.png",
},
{
    "id": 4,
    "title": "HP 975 Dual-Mode wireless Keyboard for business",
    "price": 120.00,
    "description": "Navigate your workspace with freedom and convenience. The HP 975 features dual-mode connectivity, allowing you to connect effortlessly using either Bluetooth technology or the included wireless USB receiver. Experience the ease of cable-free operation for enhanced mobility and a clutter-free desk.",
    "brand": "HP",
    "image": "images/p.keyboard1.png",
},
{
    "id": 5,
    "title": "HP 230 Wireless Keyboard",
    "price": 25.99,
    "description": "Experience the freedom of a cable-free workspace with the HP 230 Wireless Keyboard.The HP 230 features a full-sized layout with responsive and low-profile keys, delivering a quiet and comfortable typing experience.Setting up the HP 230 is a breeze with its plug-and-play design. Simply connect the included USB receiver to your computer, and you're ready to go. The straightforward installation ensures a quick and hassle-free start to your keyboard experience.",
    "brand": "HP",
    "image": "images/p.keyboard2.png",
},
{
    "id": 6,
    "title": "HyperX Alloy Core RGB-Gaming Keyboard(US Layout)",
    "price": 50.00,
    "description": "Introducing the HyperX Alloy Core RGB Gaming Keyboard with a US layout—a dynamic and customizable keyboard designed to take your gaming experience to the next level. Packed with features and boasting a striking design, this keyboard is a versatile addition to any gaming setup.Stay in control without leaving the game. The Alloy Core comes equipped with dedicated media controls, allowing you to adjust volume, play, pause, and skip tracks with ease. Quick access to these functions enhances your multitasking capabilities during intense gaming sessions.",
    "brand": "HyperX",
    "image": "images/p.keyboard3.png",
},
{
    "id": 7,
    "title": "HP 410 Slim Silver Bluetooth Mouse",
    "price": 56.55,
    "description": "The HP 410 boasts a slim and lightweight design, making it the perfect travel companion. Slip it into your bag or pocket effortlessly, and enjoy the convenience of a compact mouse that doesn't compromise on style.Say goodbye to tangled wires. The HP 410 connects seamlessly to your device via Bluetooth technology, eliminating the need for a USB receiver. Experience the freedom of wireless control without sacrificing precision.",
    "brand": "HP",
    "image": "images/P.MOUSE1.png",
},
{
    "id": 8,
    "title": "HP 280 Silent Wireless Mouse",
    "price": 25.00,
    "description": "Experience the quiet efficiency of the HP 280 Silent Mouse. The advanced silent switches ensure that every click is virtually noiseless, creating a calm and focused working environment without compromising on performance.Cut the cord and enjoy wireless freedom with the HP 280. Connect effortlessly to your device via reliable wireless technology, eliminating the need for cumbersome cables and providing a clutter-free workspace.",
    "brand": "HP",
    "image": "images/p.mouse2.png",
},
{
    "id": 9,
    "title": "HP Z3700 OYB G2 Wireless Mouse",
    "price": 24.99,
    "description": "Introducing the HP Z3700 Wireless Mouse—a sleek and reliable peripheral designed to elevate your computing experience with wireless convenience and stylish aesthetics.Cut the cords and enjoy seamless connectivity with the HP Z3700. This wireless mouse connects effortlessly to your device, providing the freedom to move and navigate without the constraints of traditional wired mice.",
    "brand": "HP",
    "image": "images/p.mouse3.png", 
},
{
    "id": 10,
    "title": "HyperX Cloud Alpha - Gaming Headset (Black-Red)",
    "price": 69.99,
    "description": "Experience rich and detailed audio with HyperX Cloud Alpha's dual-chamber drivers. The innovative design separates the bass frequencies from the mids and highs, resulting in clearer, more defined sound for a truly immersive gaming experience.",
    "brand": "HyperX",
    "image": "images/p.headphone1.png",
},
{
    "id": 11,
    "title": "HyperX Clutch-Wireless Gaming Controller (Black)-Mobile PC",
    "price": 69.99,
    "description": "Introducing the HyperX Clutch-Wireless Gaming Controller in a sleek Black color, designed for both mobile and PC gaming. This versatile gaming controller combines cutting-edge wireless technology with a comfortable ergonomic design, delivering a seamless and immersive gaming experience across various platforms.Cut the cord and enjoy the freedom of wireless gaming with the HyperX Clutch-Wireless Controller. Connect effortlessly to your mobile device or PC via Bluetooth technology, eliminating the constraints of traditional wired controllers.",
    "brand": "HyperX",
    "image": "images/p.controller1.png",
},
{
    "id": 12,
    "title": "HyperX  SoloCast - USB Microphone (Black)",
    "price": 69.99,
    "description": "Introducing the HyperX SoloCast USB Microphone in a sleek Black color—a professional-grade microphone designed for content creators, streamers, and gamers who demand exceptional audio quality. With its plug-and-play simplicity and versatile features, the HyperX SoloCast is your go-to solution for clear and crisp voice recording.Elevate your content with studio-quality sound. The HyperX SoloCast features a cardioid polar pattern that captures your voice with clarity while minimizing background noise. Whether you're streaming, podcasting, or recording, the SoloCast ensures your voice takes center stage.",
    "brand": "HyperX",
    "image": "images/p.mic1.png",
}]